### ISSUE TITLE
Having problem downloading LAION-400M Dataset using provided scripts

### ISSUE THREAD

**Issue by dddavid4real** [D0miH/does-clip-know-my-face#1]
Hi, thank you for this great work.

I'm currently trying to reproduce this work, however, I met some problems during downloading the images of the individuals that are not present in the LAION-400M dataset using your provided scripts:

`python laion400m_experiments/00_download_laion_european_non_members.py`

I met the following problem:

`HTTP Error 404: Not Found`

I believe it is because some of the urls are invalid now. Can you help me out? Thank you.

**Comment by dddavid4real** [comment]
I simply catch and skip the HTTPerror and URLerror.

**Comment by D0miH** [comment]
Hey,
yeah, unfortunately some of these images are not available anymore. 
Catching the errors is one approach. You could also manually search for additional images online and just exchange the URLs in the files. 

Best,
Dominik
